library(dplyr)
library(tidyr)
fileurl<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileurl,destfile = "helec.zip")
downloadtime<-date()
unzip("./helec.zip")
helec<-read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
selected<-c("1/2/2007","2/2/2007")
feb<-helec[helec$Date %in% selected,]
feb$Date<-as.Date(feb$Date, format = "%d/%m/%Y")
feb<-feb %>% unite (col= "datetime",Date,Time, sep = " ")
feb$datetime<-strptime(feb$datetime, format = "%Y-%m-%d %H:%M:%S")
head(feb)
feb$Global_active_power<-as.numeric(as.character(feb$Global_active_power))
feb$Global_reactive_power<-as.numeric(as.character(feb$Global_reactive_power))
feb$Voltage<-as.numeric(as.character(feb$Voltage))
feb$Global_intensity<-as.numeric(as.character(feb$Global_intensity))
feb$Sub_metering_1<-as.numeric(as.character(feb$Sub_metering_1))
feb$Sub_metering_2<-as.numeric(as.character(feb$Sub_metering_2))
feb$Sub_metering_3<-as.numeric(as.character(feb$Sub_metering_3))